### ISSUE TITLE
Game Graphics

### ISSUE THREAD

**Issue by CostaAnthony** [CostaAnthony/LostInTheSauce#10]
the game looks bland so far, someone will need to upload some pictures and graphics to each level so that it looks nicer and higher quality.

**Comment by umersiddiqi-school** [comment]
I'm gonna start working on this, I'll start researching some backgrounds/themes for our levels. I'm thinking a beach theme for one of the levels, still deciding on the other two. I'll start researching sprites too.

**Comment by CostaAnthony** [comment]
Umer added all the Sprites for every level and made the level look more like a finished product. Completed 5/4/2024.
